name: Docker Image CI

on:
  release:
    types:
    - published
  workflow_dispatch:

jobs:

  build:
    if: startsWith(github.event.ref, 'refs/tags')
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build & Push Image
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: |
          ghcr.io/randy-halim/discord-ai-summarization:latest
          ghcr.io/randy-halim/discord-ai-summarization:{{version}}
    
    
